"""PlatformIO pre-script: regenerate src/build_info.cpp with GIT_HASH and BUILD_DATE.

The values are emitted as `extern const char *const` definitions instead of
CPPDEFINES so they only invalidate build_info.cpp.o — not every translation
unit in the project. With CPPDEFINES the SCons environment signature changed
every build (BUILD_DATE is second-precision), forcing a full recompile of
~80 framework/library/src files on every `pio run`. This way only one .cpp
recompiles + relink.

src/util.cpp declares matching externs and consumes them in util_version_string().
The generated file is listed in .gitignore.
"""
from datetime import datetime
from pathlib import Path
import subprocess

Import("env")  # noqa: F821 — provided by SCons / PlatformIO


def _git_short_hash() -> str:
    try:
        commit = subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"],
            stderr=subprocess.DEVNULL,
        ).strip().decode()
        dirty = subprocess.check_output(
            ["git", "status", "--porcelain"],
            stderr=subprocess.DEVNULL,
        ).strip()
        return commit + ("-dirty" if dirty else "")
    except Exception:
        return "unknown"


git_hash = _git_short_hash()
build_date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

# C-escape: only " and \ are realistically reachable from these inputs, but
# guard anyway so a stray character never breaks the build.
def _c_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


contents = (
    "// AUTO-GENERATED by scripts/inject_build_info.py — do not edit by hand.\n"
    "// Regenerated on every `pio run`; gitignored.\n"
    "\n"
    f'extern const char *const BUILD_INFO_GIT_HASH   = "{_c_escape(git_hash)}";\n'
    f'extern const char *const BUILD_INFO_BUILD_DATE = "{_c_escape(build_date)}";\n'
)

target = Path(env.subst("$PROJECT_SRC_DIR")) / "build_info.cpp"  # noqa: F821
# Only rewrite when content actually differs — keeps mtime stable on no-op runs
# so SCons doesn't relink when nothing changed (e.g. two `pio run` in the same
# second). Practical impact is small since BUILD_DATE almost always differs.
if not target.exists() or target.read_text(encoding="utf-8") != contents:
    target.write_text(contents, encoding="utf-8")

print(f"[inject_build_info] GIT_HASH={git_hash}  BUILD_DATE={build_date}")
